name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build Docker Image
      run: |
        docker build -t parzivall/docker-graphq:0.0.2 .

    - name: Push Docker Image
      run: |
        docker push parzivall/docker-graphq:0.0.2 .
    
    # - name: Build Docker Image
    #   env:
    #     NEW_VERSION: ${{ steps.version.outputs.version }}
    #   run: |
    #     docker build -t parzivall/docker-graphql:$NEW_VERSION .
    #     docker build -t parzivall/docker-graphql:latest .
        
    # - name: Push Docker Image
    #   env:
    #     NEW_VERSION: ${{ steps.version.outputs.version }}
    #   run: |
    #     docker push parzivall/docker-graphql:$NEW_VERSION
    #     docker push parzivall/docker-graphql:latest
    
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
